#!/usr/bin/env bash
ETH1_IP=10.1.1.104

# allow an internal IP to access the external network
iptables --insert FORWARD --source $1 -j ACCEPT
iptables --insert FORWARD --destination $1 --match state --state ESTABLISHED -j ACCEPT
iptables -t nat --insert PREROUTING --source $1 -j ACCEPT
iptables -t nat --insert POSTROUTING --source $1 --out-interface eth1 -j SNAT --to-source $ETH1_IP
