maple('Restart()');

maple(['DeclareObservers('...
    'W,'...
    'Base,'...
    'UpperArm,'...
    'AuxArm,'...
    'LowerArm,'...
    'Foot)']);

maple(['DeclarePoints('...
    'W,'...
    'Base,'...
    'UpperArm,'...
    'AuxArm,'...
    'LowerArm,'...
    'Foot)']);

maple(['DeclareTriads('...
    'w,'...
    'base,'...
    'upperarm,'...
    'lowerarm,'...
    'foot)']);

maple('s:=1');

maple(['DefineNeighbors('...
    '[W,Base],'...
    '[Base,UpperArm],'...
    '[Base,AuxArm],'...
    '[UpperArm,LowerArm],'...
    '[LowerArm,Foot])']);

maple(['DefineObservers('...
    '[W,W,w],'...
    '[Base,Base,base],'...
    '[UpperArm,UpperArm,upperarm],'...
    '[AuxArm,AuxArm,upperarm],'...
    '[LowerArm,LowerArm,lowerarm],'...
    '[Foot,Foot,foot])']);

maple(['DefinePoints('...
    '[W,Base,w,q1,q2,q3],'...
    '[Base,UpperArm,base,1,0,1],'...
    '[Base,AuxArm,base,0,-2*s,0],'...
    '[UpperArm,LowerArm,upperarm,0,0,7*s],'...
    '[LowerArm,Foot,lowerarm,0,0,7*s])']);

maple(['DefineTriads('...
    '[w,base,[q4,3],[q5,1],[q6,3]],'...
    '[base,upperarm,[q7,2],[p1,3],[p2,1]],'...
    '[upperarm,lowerarm,q8,2],'...
    '[lowerarm,foot,[q9,2],[q10,1]])']);

maple(['DefineObjects('...
    '[Base,''Block'',xlength=2,ylength=1,zlength=4,color=red],'...
    '[UpperArm,''Cylinder'',point=MakeTranslations(upperarm,0,0,3.5*s),'...
        'length=7*s,radius=0.1],'...
    '[LowerArm,''Cylinder'',point=MakeTranslations(lowerarm,0,0,3.5*s),'...
        'length=7*s,radius=0.1],'...
    '[Foot,''Cylinder'',length=0.1,radius=1*s])']);

% constraints
maple('f1:=MakeTranslations(foot,3) &oo MakeTranslations(w,1)=0');
maple('f2:=MakeTranslations(foot,3) &oo MakeTranslations(w,3)=0');

maple('f3:=LinearVelocity(W,Foot) &oo MakeTranslations(w,1)=0');
maple('f4:=LinearVelocity(W,Foot) &oo MakeTranslations(w,2)=0');
maple('f5:=LinearVelocity(W,Foot) &oo MakeTranslations(w,3)=0');

maple(['kde:={'...
    'seq(LinearVelocity(W,Base) &oo MakeTranslations(w,i)=cat(u,i),i=1..3),'...
    'seq(AngularVelocity(w,base) &oo MakeTranslations(w,i)=cat(u,i+3),i=1..3),'...
    'AngularVelocity(base,upperarm) &oo MakeTranslations(base,2)=u7,'...
    'AngularVelocity(upperarm,lowerarm) &oo MakeTranslations(upperarm,2)=u8}'...
    'union DiffTime({f1,f2})']);

%maple(['footmove:={'...

maple(['GeometryOutput('...
    'main=W,'...
    'states=[q1,q2,q3,q4,q5,q6,q7=0.2,q8=1,q9=0.571,q10=0],'...
    'parameters=[p1=1.58,p2],'...
    'filename="leg.geo")']);

maple(['MotionOutput(ode=kde,'...
    'states=[q1,q2,q3,q4,q5,q6,q7=0.2,q8=1,q9=0.571,q10=0],'...
    'parameters=[p1=1.58,p2],'...
    'insignals=[u1=0,u2=0,u3=0,u4=0,'...
        'u5=0,u6=0,u7=0,u8=0],'...
    'filename="leg.dyn")']);